"""
Markdown memo writer for Deal Advisor Intelligence Engine.
"""

from datetime import datetime, timezone
from .schemas import DealResearchRequest, DealMemo, Source
from .research_plan import build_research_plan, estimate_token_usage
from .scoring import score_deal


def _score_table(scorecard) -> str:
    rows = ["| Dimension | Score | Confidence | Key Evidence | Key Risks |", "|---|---:|---:|---|---|"]
    for d in scorecard.dimensions():
        evidence = "<br>".join(d.evidence[:3]) if d.evidence else "-"
        risks = "<br>".join(d.risks[:3]) if d.risks else "-"
        rows.append(f"| {d.name} | {d.score:.1f}/10 | {d.confidence:.2f} | {evidence} | {risks} |")
    return "\n".join(rows)


def build_deal_memo(request: DealResearchRequest, research_notes: str = "") -> DealMemo:
    plan = build_research_plan(request)
    query_count = sum(len(v) for v in plan.values())
    token_estimate = estimate_token_usage(request, query_count)
    scorecard = score_deal(request, research_notes)
    recommendation = scorecard.recommendation

    summary = (
        f"{request.target} is evaluated as a {request.deal_type.value.replace('_', ' ')} opportunity in the "
        f"{request.sector} sector. The current offline score is {scorecard.overall_score}/10 with "
        f"{scorecard.overall_confidence:.2f} confidence. The preliminary recommendation is **{recommendation}**. "
        "This memo is generated by the Deal Advisor Intelligence Engine MVP; live GPT-Researcher retrieval can replace the offline notes layer for cited evidence."
    )

    research_questions = [q for queries in plan.values() for q in queries]

    return DealMemo(
        title=f"Deal Memo: {request.target}",
        executive_summary=summary,
        company_overview=(
            f"Target: **{request.target}**. Sector: **{request.sector}**. "
            f"Deal type: **{request.deal_type.value}**. Investment question: {request.investment_question}. "
            f"Regions considered: {', '.join(request.regions)}."
        ),
        market_analysis=(
            "The research plan prioritizes market size, category growth, adoption curves, customer urgency, and regional expansion dynamics. "
            "For MiMo deep-mode runs, each market hypothesis is recursively checked against analyst reports, news, customer signals, and competitor movement."
        ),
        competitive_landscape=(
            "The engine maps direct competitors, substitutes, incumbents, pricing pressure, distribution advantages, and defensibility. "
            f"Initial comparable set: {', '.join(request.comparables) if request.comparables else 'auto-generated from sector queries'}."
        ),
        business_model=(
            "Business model evaluation covers pricing, customer segment, gross margin hypothesis, sales motion, retention, and possible expansion loops. "
            "Private-company financial data is treated as low-confidence unless verified from credible sources."
        ),
        team_analysis=(
            "Team analysis checks founder-market fit, prior exits, technical depth, hiring velocity, leadership stability, and reputational risk. "
            "The MVP marks this dimension as medium/low confidence until live source retrieval is enabled."
        ),
        financial_overview=(
            "Financial overview evaluates funding history, valuation trajectory, revenue/profitability clues, burn/runway risk, and capital intensity. "
            "When public filings are unavailable, the system highlights evidence gaps instead of fabricating numbers."
        ),
        traction_metrics=(
            "Traction analysis searches for revenue, ARR, user growth, customer logos, partnerships, web/app traffic, hiring growth, and community activity. "
            "Each signal is weighted by recency and source quality."
        ),
        risk_analysis=(
            "Risk analysis covers regulatory exposure, privacy/security issues, platform dependency, competitive compression, execution risk, and valuation risk. "
            "The scorer is intentionally conservative when evidence is sparse."
        ),
        investment_thesis=(
            f"Preliminary thesis: {request.target} deserves deeper diligence if live research validates strong demand, credible traction, and defensibility. "
            "The next step is to run a full GPT-Researcher source-gathering pass and then rerun the scoring agent with citations."
        ),
        recommendation=recommendation,
        scorecard=scorecard,
        sources=[
            Source(url="local://research-plan", title="Generated Research Plan", snippet="Offline MVP generated due diligence query map", relevance=1.0, source_type="internal"),
            Source(url="local://scoring-engine", title="Deterministic Scoring Fallback", snippet="MVP scoring layer for proof/demo without paid API calls", relevance=0.8, source_type="internal"),
        ],
        research_questions=research_questions,
        token_usage_estimate=token_estimate,
    )


def render_markdown(memo: DealMemo) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    qs = "\n".join(f"- {q}" for q in memo.research_questions)
    sources = "\n".join(f"- [{s.title}]({s.url}) — {s.snippet}" for s in memo.sources)
    return f"""# {memo.title}

Generated: {now}  
Engine: Deal Advisor Intelligence Engine fork for GPT-Researcher  
Recommendation: **{memo.recommendation}**  
Overall Score: **{memo.scorecard.overall_score}/10**  
Overall Confidence: **{memo.scorecard.overall_confidence:.2f}**  
Estimated Deep Research Token Budget: **{memo.token_usage_estimate:,} tokens**

## 1. Executive Summary

{memo.executive_summary}

## 2. Company Overview

{memo.company_overview}

## 3. Scorecard

{_score_table(memo.scorecard)}

## 4. Market Analysis

{memo.market_analysis}

## 5. Competitive Landscape

{memo.competitive_landscape}

## 6. Business Model

{memo.business_model}

## 7. Team Analysis

{memo.team_analysis}

## 8. Financial Overview

{memo.financial_overview}

## 9. Traction Metrics

{memo.traction_metrics}

## 10. Risk Analysis

{memo.risk_analysis}

## 11. Investment Thesis

{memo.investment_thesis}

## 12. Research Query Plan

{qs}

## 13. Sources / Evidence Layer

{sources}

## 14. Production Integration Notes

This MVP can run offline for demo/proof purposes. In production, each query from the research plan is handed to GPT-Researcher's existing retrieval, scraping, summarization, reviewer, and publisher pipeline. MiMo can be configured through an OpenAI-compatible endpoint using `OPENAI_BASE_URL` / `DEAL_ADVISOR_BASE_URL`, enabling high-token recursive research loops for deal diligence.
"""
